### PR TITLE
Updates readme & cleanup

### PR DESCRIPTION
**Pull request by koalalorenzo**
Updates the readme to add more info of the idea, the project background and authors.
This will also remove unnecessary files.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
I will add the reviewers as soon as the PR is not WIP

**Comment by Visardy** [comment]
Nice!

**Comment by SocialXchangedesign** [comment]
Thanks for uploading it! Let me know how the idea spreads in your organization!

**Comment by hodgson-neil** [comment]
lgtm

**Pull request merged**
